### PR TITLE
pkmaster23 feature

### PR DESCRIPTION
**Pull request by PKMaster23**
I have added my personal page. :)

### CODE REVIEW

**Review by JamesF243 — CHANGES_REQUESTED** [review]
def pkmaster in the page controller needs to be in the class, and have "render html page"

**Review by Agarnerman — DISMISSED** [review]
LGTM

**Review by Kagwyn — APPROVED** [review]
Fixed everything up. Good job!

**Review by Agarnerman — APPROVED** [review]
LGTM

**Review by JamesF243 — APPROVED** [review]

**Pull request merged**
